### ISSUE TITLE
Problem l10n_ru.xml

### ISSUE THREAD

**Issue by ALVLSH** [Ls-Modcompany/FS19_GlobalCompany#109]
At the moment, the l10n_ru.xml file does not match the contents of the l10n_en.xml file. Most likely it belongs to another project Ls-Modcompany / FS19_GlobalCompanyAddOn_FieldLease

**Comment by Gonimy-Vetrom** [comment]
I confirm. Now everyone has this error on the Official website.

**Comment by ArtV-Nef** [comment]
GC was updated to version 1.6.0 - and all the texts fell off :(
