### ISSUE TITLE
issue for mod "LIZARD pig feeding systems" who can help? -issue für mod "LIZARD pig feeding systems" wer kann helfen?

### ISSUE THREAD

**Issue by haamic** [Ls-Modcompany/FS19_GlobalCompany#125]
Hello,
I'm testing the "LIZARD pig feeding systems mod" (author: LS-Modcompany / D-S_Agrarservice - Kastor / kevink98).
Who is the contact person for this? can you give me contact details, or am I in the right place?
I can fill each of the four silos, the displays show the amount filled.
But in the menu only corn of the 1st silo is shown, the other 3 fruits are missing.
For testing I only have this mod and GC in the mod folder.
What have I possibly done wrong, or is the error known?
Greetings Micha

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Hallo,
ich teste gerade den mod "LIZARD pig feeding systems". (author: LS-Modcompany / D-S_Agrarservice - Kastor / kevink98)
Wer ist dafür Ansprechpartner? könnt ihr mir Kontaktdaten geben, oder bin ich hier bereits richtig?
Ich kann jeden der vier Silos befüllen, auf den anzeigen steht die eingefüllte Menge.
Im menü allerdings wird mir nur Mais, des 1. Silo angezeigt, die anderen 3 Früchte fehlen.
Zum Test hab ich nur diesen Mod und GC im mod-Ordner.
Was hab ich evtl. falsch gemacht, bzw. ist der Fehler bekannt?
Gruss Micha

![pigfeed](https://user-images.githubusercontent.com/28841989/89715930-88708f80-d9a9-11ea-8940-13d342dda692.jpg)

**Comment by haamic** [comment]
sorry mein fehler, dachte im Hauptmodul sehe ich alle eingefüllten früchte, da ich ja dort auch alle einfülle.
jeder silo hat ein eigenes Menü

**Comment by iwan4672** [comment]
> 
> 
> sorry mein fehler, dachte im Hauptmodul sehe ich alle eingefüllten früchte, da ich ja dort auch alle einfülle.
> jeder silo hat ein eigenes Menü

You have to every of 4 silos approaches and on every to display statistics and setting
