### ISSUE TITLE
Object Info

### ISSUE THREAD

**Issue by GtX-Andy** [Ls-Modcompany/FS19_GlobalCompany#25]
1: There is an error given when object is deleted when you are displaying the info.
2: If a Giants GUI or one of our Full GUI screens (Main, Large Factory, Large Baler) is opened then this should also not be displaying on the screen.
3: UI does not go away if you are looking at an object and disable the script in the main menu.

2 and 3 maybe fixed when the GUI items are looked at :-)

**Comment by StachuMods** [comment]
Hi GtX! How Can I send you e-mail for support your work in FS19 modding? Do you have any e-mail for contact? Regards :)
