### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by Roby1164** [Ls-Modcompany/FS19_GlobalCompany#43]
Trying to do the translations of the various mods connected to GC, I am having problems that, some voices are not taken, I cannot understand if the problem is in the GC or in some lack on the part of the modders. Because of the various factories, where the various items that appear in the hud, a part is regularly translated, while others remain systematically only and always in German.
I put an image to try to explain better, where the voices are shown, that the translations are inserted in the xml file, but in the game, they are always in German.
https://prnt.sc/ppcywg

**Comment by liuzhenyu811** [comment]
I think you may modified the wrong place. Maybe the key has been modified not the value.
Or the language file used by the mod have some trouble.
I also tried to do a lot of translation, nothing wrong. So I don't think it's GC’s fault.
Can you provide more clues?

**Comment by Gonimy-Vetrom** [comment]
I have the same problem for the Russian language. Even the names of standard cultures in English.

**Comment by Rudolfet** [comment]
In the Culture and production is the file xlm on the maps folder too translate.
