### ISSUE TITLE
Error: Server:registerObjectInStream is only allowed in writeStream calls

### ISSUE THREAD

**Issue by WestfalenerAgrarvideos** [Ls-Modcompany/FS19_GlobalCompany#51]
Moin haben heute mal die neue Version von GC getestet dabei ist aufgegfallen das es jetzt noch mehr errors gibt als vorher 
Wenn ein Mitspieler auf den Server joind haut er den Error:Error: Server:registerObjectInStream is only allowed in writeStream calls
253 mal raus vorher waren es nur 5 mal ich dachte das wurde gefixt.
Gibt es da ne Grund für das das jetzt so extrem ist?

**Comment by kevink98** [comment]
-> Mit Version 1.1.3.0 nochmal testen!

**Comment by WestfalenerAgrarvideos** [comment]
Moin also bislang keine Probleme mehr scheint alles zu laufen danke dafür
