### ISSUE TITLE
Dedi Server bug - befüllung von Produktionen funktioniert nicht

### ISSUE THREAD

**Issue by SnackyWell** [Ls-Modcompany/FS19_GlobalCompany#53]
Moin,

Bei unserem Dedi Server wurde auf die Version 1.1.2.0 von Global Company upgedated 
nach dem update haben wir festgestellt das wir keine Produktionen oder lager mehr befüllen konnten die mit Global Company zu tun haben.
im Anschluss haben wir versucht über das Menü die Produktionen zu füllen Silage/Gülle/Mist nichts hat funktioniert nun sind wir wieder auf die Version 1.1.0.0 zurück gegangen und haben bemerkt das dann alles angezeigt wird was wir in dem spiel vorher gekauft / aufgefüllt haben.
die Produktionen fingen dann an zu arbeiten vorher (mit v. 1.1.2.0) leider nicht ich vermute mal ein anzeige Bug oder ähnliches.

**Comment by kevink98** [comment]
-> Mit Version 1.1.3.0 nochmal testen!

**Comment by SnackyWell** [comment]
is fixed :)
