### ISSUE TITLE
Warning (script): Unknown entity id 0 in method 'setOverlayRotation'.

### ISSUE THREAD

**Issue by Mannie313** [Ls-Modcompany/FS19_GlobalCompany#59]
[log.txt](https://github.com/Ls-Modcompany/FS19_GlobalCompany/files/3818609/log.txt)

MFG Mannie313

**Comment by kevink98** [comment]
![image](https://user-images.githubusercontent.com/36474411/69562641-e4c48800-0faf-11ea-8a2d-2e670157800f.png)

Lesen hilft!
