### ISSUE TITLE
Produktionsgeschwindigkeit verdoppelt

### ISSUE THREAD

**Issue by Lars-LS17** [Ls-Modcompany/FS19_GlobalCompany#73]
Hallo Zusammen,

ich habe in den letzten Updates ein Bug festgestellt. 
Alle Produktionen haben eine Doppelte Produktionsgeschwindigkeit pro Stunde.
In der Version 1.1.3.0 ist dieses Problem noch nicht. In allen neueren Versionen hat sich die Masse pro Stunde verdoppelte. In der XML-Datei von der Produktion steht bei OutputperHour=6000
Im Spiel wird aber die Geschwindigkeit von 12.000 angezeigt.

**Comment by derelky** [comment]
Spielst du mit Seasons?
Wenn ja erklärt sich das hier durch:
![image](https://user-images.githubusercontent.com/32611431/71966886-ad7a0580-3202-11ea-8a3e-f443902e9598.png)

**Comment by Lars-LS17** [comment]
Ja spiele ich.
Dann entschuldige ich mich.
Diese Funktion wusste ich gar nicht. 
Vielen Dank. 
ich schließe das Issue.
