### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Blackjack155** [Ls-Modcompany/FS19_GlobalCompany#77]
Error: Running LUA method 'GC_ProductionFactory.onCreate'.
FS19_GlobalCompany/objects/GC_ProductionFactory.lua:290: attempt to index local 'allowSubType' (a nil value)
2020-01-03 02:17 Error: Corrupt savegame, onCreateLoadedObject 18 has invalid saveId 'globalCompany_Schlachthof'

**Comment by Berzerk70** [comment]
gleiche problem hab ich auch mit der nfmarsch und der schlachterei...plazierte ist weg und kann keine bauen ..ausserdem kackt das spiel dann ganz ab...bis version 1.1.4 ist alles ok

**Comment by Opa-Andre** [comment]
@Berzerk70 : Nimm die aktuelle GC Version 1.1.5.1 - damit geht es wieder.

**Comment by Berzerk70** [comment]
ja hab genommen...super läuft alles...danke für schnelle update

lg stefan

**Comment by Berzerk70** [comment]
Also schlachterei geht zwar soweit aber tiere (schweine in moment) werden nicht angenommen...bleiben im hänger

**Comment by Blackjack155** [comment]
Also mom läuft es. habe aber die schlachterei auch noch nicht als Produktzion angechlossen.

**Comment by bandit2075** [comment]
Bei mir klappt es mit den Schweinen auch nicht. GC 1.2.0.0
