### ISSUE TITLE
Rohstoff Verkauf im MP Dedi Server

### ISSUE THREAD

**Issue by Gyffes** [Ls-Modcompany/FS19_GlobalCompany#81]
Grüße und Hallo, 

Ich bin mir nicht sicher ob es überhaupt ein Fehler ist oder nur ein wunsch von mir :-)

Wir haben auf unseren kleinen Dei Server auch die GC Drauf gemacht da es einfach eine Spitzten Erweiterung zum Game ist. Danke dafür erstmal. 
Nun ist uns aufgefallen wenn Spieler A zb das Sägewerk besitzt und Spieler B an diesem Sägewerk Holz abliefert wird dem Spieler kein Geld gutgeschrieben.  Ist dies Gewolt oder ein Fehler. 
Falls es kein Fehler ist wovon ich mittlerweile ausgehen. Würd ich das gern als Wunsch hierlassen. 
Wäre Mega wenn man in den Einstellungen zb einen Preis Pro Liter hinterlegen könnte. Der dann von Spielerkonto Abgezogen wird. Kleine Option in der man die Annahme von Ware von anderen Spielern verweigert sollte dann nur nicht fehlen. 

Wünsche allen einen schönen Abend. 

Danke für die Mod.

**Comment by SvenDee** [comment]
Dies ist kein Fehler sondern so vom Spiel so gewollt. Es ist auch kein Global Company Problem sondern einfach eine Vanilla Game Mechanik zum Handel unter Spielern bzw. Lohnunternehmerstatus.
Der Besitz der Ware ist hier entscheidend. Wenn ich als Beispiel mit meinem Fahrzeugen bei einen anderen Spieler die Ware abhole, wechselt diese in meinen Besitz.  Zum aufladen wird der Lohnunternehmerstatus benötigt. (Szenario 2) 
Das erste Szenario ist somit nur zum Transport der Ware. Man stellt dann quasi nur einen Fahrer ein, der die Waren von A nach B bringt/holt/verkauft. 

Wahrscheinlich spielt Ihr mit mehreren Höfen (jeder Spieler hat seinen eigenen Hof).
Szenario 1: Spieler A besitzt das Sägewerk und gibt Spieler B Lohnunternehmerstatus. Spieler B nutzt die Fahrzeuge von Spieler A und lädt ab.  Es fliesst kein Geld auf das Konto von Spieler B, da die Ware weiterhin Spieler A gehört. Spieler A bekommt somit auf dem Verkaufstrigger das Geld. Spieler B ist hier jediglich als Fahrer angestellt. 

Szenario 2: Spieler A besitzt auch hier das Sägewerk und gibt Spieler B Lohnunternehmerstatus, allerdings nutzt Spieler B seine eigenen Fahrzeuge.  Hier bekommt Spieler B am Verkaufstrigger Geld bekommen, da Ihm die Ware gehört sobald er diese mit seinen Fahrzeugen aufnimmt. (Ware wechselt den Besitzer)

**Comment by Gyffes** [comment]
Danke für deine Info. Das ist schon mal gut zu wissen. 
Werden das noch mal Probieren und beobachten.

Wir spielen eigentlich mit Vatiante 2 gespielt. Nur hat Spieler B eben kein Geld bekommen. 

Ich werd berichten. 

Danke

**Comment by SvenDee** [comment]
Bitte. Falls der Fehler weiter besteht bitte GC Version, Map bzw Mod (Sägewerk) falls nicht auf der Map verbaut hinzufügen. Dann schau ich mir das mal an.

**Comment by Gyffes** [comment]
Gruße 
hatte etwas gedauert um es nochmal zu Testen dann war aber hier die Github seite nicht mehr da, 

Problem besteht weiterhin.
GC Version 1.3.0 mit der Dondiego Map V 2.1.1 Die gebäude sind da schon fest Verbaut.

Hatte anfang Februar auch da mal nachgegfragt aber bisher keine Antwort erhalten. 
Vielen Dank das Ihr Euch dem Problem annehmt.

**Comment by kevink98** [comment]
Ist kein Fehler, die Fabriken sind auch keine Verkaufsstelle.

**Comment by Gyffes** [comment]
Super vielen Dank für die Info. Gibt es eine Möglichkeit das ich das ändern kann? 
Und wenn ja wo.

Danke Dir. 
Bleibt gesund.

**Comment by kevink98** [comment]
Na du kannst ne ganz normale Verkaufsstelle machen. Oder das Holz liefern und die Person, der das Sägewerk gehört überweist dir Geld. So ist aber das Spielprinzip vom LS.

**Comment by Gyffes** [comment]
Ok danke Dir. Hatte gehofft das man es im MP Dedi bissel interaktiver machen könnte. (Globel market geht ja nicht)  Aber dann muss es so gehen. 

Danke Dir für die Hilfe.
