### ISSUE TITLE
Global Market Dedicated Root Server Problem with the Keybind R GM 1.3.0.1

### ISSUE THREAD

**Issue by Justice-Molton** [Ls-Modcompany/FS19_GlobalCompany#83]
Hello, 
we've got the problem that as soon as we opened the GM Menue once, we can open it from everywhere on the map. That causes the problem we couldn't open eg the repair triggers. because as actual action is always the open global market the option. 
We have some Autodrive Markers around the GM, could this cause the Problem?

**Comment by kevink98** [comment]
This is a generelly problem, when you are in a trigger then you tab in a vehicle, than have you this effect.
