### ISSUE TITLE
Feature Request: Release Market exe server/client code.

### ISSUE THREAD

**Issue by 74656b** [Ls-Modcompany/FS19_GlobalCompany#85]
This request has a few different facets. By releasing the server code, it would allow communities of players to be able to host their own private market instances that are immune to the malicious acts of others, but also keep their market to a smaller more focused scale.

In one use case, there are users who prefer to play in the single player mode but still want to have some link to their friends who also play single player. A privately hosted instance would enable this.

Furthermore, the more prominent use case would be groups of multiplayer servers that center around streamer communities. Typically this is a small group of streamers who are all friends, and share viewers/players between them. In this case they would be able to host a market instance between their multiplayer communities that they play with. Additionally, this enables multiple independent farms on the same server to be able to buy and sell goods between each other on the same server, thus avoiding the painful "ownership" that's attached to bales and other objects.

If you do not want to release the server code, my request would be to create a site that would permit the creation of private market instances. A user could sign up to create a private market instance, generating a token(api key) that they could provide to their players. Additionally, create a web interface to allow the instance owner to oversee transactions and create manual adjustments or overrides to commodity prices. This could even be monetized for a monthly subscription since you would be doing the hosting.

**Comment by kevink98** [comment]
Hey, thank you for your request.

I though about this points. But when i release the servercode, than its very easy to cheat without game.

Its nice when we have a serverpage who you can login and create a own server. But its some work for that... 

We will see what way we go in the future.

**Comment by Stephan-S** [comment]
The original version of Global market (FS17) already had community instances built into it.
I personally think this was an elegant solution. A user could simply input a name (for the server / group) and a password in the config file. This would of course now be realized in the nice gui tool instead of a config file.

The server would then always synchronize everything to that instance. And if left blank/default to the actual global instance. If the instance name was not yet 'registered' at the server, it got created with the provided password, when the user first connected.

**Comment by 74656b** [comment]
Stephan,
 Your solution sounds very elegant! It would be a great first step towards community instances in the FS19 version.

**Comment by kevink98** [comment]
Now you can create your own server with the exe. I think i can now close this request.
