### ISSUE TITLE
GC_AnimalLoadingTrigger.lua:339

### ISSUE THREAD

**Issue by Torben833** [Ls-Modcompany/FS19_GlobalCompany#89]
2020-03-10 16:42 C://gameservers//s1338441//ls2019//gameProfile/mods/FS19_GlobalCompany/triggers/GC_AnimalLoadingTrigger.lua:339: attempt to index field 'activatedTarget' (a nil value)

Seit dem FED Mods eine Rinderzucht veröffentlicht hat, nutze ich diese.

Allerdings kann ich auf unserem Dedi-Server keine Rinder aus der Rinderzucht entnehmen, im Singleplayer aber schon.

Was könnte der FEhler bedeuten oder wie werde ich diesen los?

Freundliche Grüße

Torben

**Comment by Tornado1975** [comment]
Gibt es schon ne lösung ???

**Comment by bandit2075** [comment]
Selbst mit der Version 1.4.0.0 von Modhub taucht der Fehler auf den Server auf

**Comment by TethysSaturn** [comment]
Der Fehler dass man keine Tiere auslagern kann besteht nur bei einem Dedi-Server. Als Zwischenlösung kann man das Savegame lokal speichern und ein lokales Multiplayerspiel starten. Hier lassen sich die Tiere entnehmen. danach das Spiel speichern und das Savegame wieder auf den Dedi laden. Sehr umständlich aber besser wie gar keine Funktion.
