### ISSUE TITLE
Request: Detailed text for Dynamic-Storage-Boxes

### ISSUE THREAD

**Issue by FSpAre** [Ls-Modcompany/FS19_GlobalCompany#93]
At the moment, if the boxes are empty, only the word "empty" is displayed for each box. It is not possible for the user to see which capacity each box has. If there are silos with different max. storage amounts.
So therefore it could happen, that the user choose the wrong (to small or to big) box for storing his harvest.

I would recommend to display under line with "empty" a line below with the max. storage amount. Example:
```
   empty
0/1.250.000
```

Also it would be nice to be able to customize the text in the dynstorage menu. To put a more specific discription for the silo-types and what the user can do with them.

**Comment by kevink98** [comment]
Now the capacity will print always on the screen.

For more specific discription is actually no space^^
