### ISSUE TITLE
Fehler in der Log

### ISSUE THREAD

**Issue by hassel84** [Ls-Modcompany/FS19_GlobalCompany#95]
Moin 

Wenn ich den Mod einfüg und das Savegame lade, kommt ein riesiger abschnitt in meiner Log Datei mit einen Error.

Leider werde ich nicht schlau draus. Hab schon versucht den Mod zu finden der das verursacht, hab aber erstmal aufgegeben. 

Die Version die ich wollte ist die hier von Github. und bei der Versin von Modhub das gleiche Problem.

anbei mal meine Log evtl findet einer den fehler.

Danke

[log.txt](https://github.com/Ls-Modcompany/FS19_GlobalCompany/files/4499184/log.txt)

**Comment by bizzybone88** [comment]
Das liegt nicht am GlobalCompany Mod sondern am ManureSystem. Du hast Version 1.0.0.0 die neuster Version ist aber die 1.0.9.0.

**Comment by hassel84** [comment]
danke für den Tip. Aber daran hat es nicht gelegen.

**Comment by kevink98** [comment]
Probiere doch mal die neuste Version von hier, oder:
GC entfernen, savegame starten+speichern
Spiel neu starten, GC wieder auswählen

**Comment by hassel84** [comment]
danke Problem ist gelöst
